### ISSUE TITLE
Can't Instantiate Client Object

### ISSUE THREAD

**Issue by nogreintel** [opus-42/superset-api-client#1]
# Problem Description 
I am developing within an AWS Cloud9 environment. I have Superset deployed inside of an EKS cluster via a helm chart per the documentation [1].

# Steps to Reproduce
I expose Superset on port 8080:
```
kubectl port-forward service/superset 8080:8088 --namespace default
```
I then run the code suggested on this repository's README:

``` python
from supersetapiclient.client import SupersetClient

client = SupersetClient(
    host="http://localhost:8080",
    username="admin",
    password="admin",
)
```
This then results in the error:
```
Traceback (most recent call last):
  File "superset-api-client.py", line 6, in <module>
    password="admin",
  File "/home/ec2-user/.local/share/virtualenvs/environment-QZ1wNgYc/lib/python3.7/site-packages/supersetapiclient/client.py", line 64, in __init__
    self.charts = Charts(self)
  File "/home/ec2-user/.local/share/virtualenvs/environment-QZ1wNgYc/lib/python3.7/site-packages/supersetapiclient/base.py", line 106, in __init__
    for e in infos.get("edit_columns")
TypeError: 'NoneType' object is not iterable
```

# Trouble Shooting Steps

In order to find out why `infos.get("edit_columns")` resulted in a NoneType object, I stepped through the Python debugger. 

The error starts [here](https://github.com/opus-42/superset-api-client/blob/850a9070fcf37bb58492a2726f9838e71d278413/supersetapiclient/client.py#L64) in the client constructor. Charts which [inherits from ObjectFactories in base.py](https://github.com/opus-42/superset-api-client/blob/850a9070fcf37bb58492a2726f9838e71d278413/supersetapiclient/charts.py#L25) and ultimately results in calling the api `GET /chart​/_info`.

The specific url which we end up trying access  is 'http://localhost:8080/api/v1/chart/_info` via superset-api-client. 

In order to validate this, we tried to access the same url with the requests library while the debugger was paused at base.py in [line 103](https://github.com/opus-42/superset-api-client/blob/850a9070fcf37bb58492a2726f9838e71d278413/supersetapiclient/base.py#L103). We then entered an interactive shell and ran the following tests with pdb. 

## Test 1 (Duplicating the error)
``` python
import requests
import json
url = client.join_urls(self.base_url, "_info")  #self is the chart object
#url = 'http://localhost:8080/api/v1/chart/_info'
r = requests.get(url, headers = client._headers) #client is the superset client object
print(r.status_code) #r.status_code = 500
print(r.text) #r.text = '{"message":"Fatal error"}\n'
```
## Test 2 (Adding Query)
In the UI for the Superset API, http://localhost:8080/swagger/v1, 
![image](https://user-images.githubusercontent.com/86027667/136616042-b5ba237f-d05c-4adb-9c3b-51d0b638dd0c.png)
A query object is added to the get request and it succeeds
![image](https://user-images.githubusercontent.com/86027667/136616218-87552186-7537-4a3c-9fd9-dd412d9b625b.png)
We attempt to recreate while still in the debugger by modifying the request.
``` python
import requests
import json
url = client.join_urls(self.base_url, "_info")  #self is the chart object
#url => 'http://localhost:8080/api/v1/chart/_info'
query = {
  "add_columns": {
    "additionalProp1": {
      "page": 0,
      "page_size": 0
    },
    "additionalProp2": {
      "page": 0,
      "page_size": 0
    },
    "additionalProp3": {
      "page": 0,
      "page_size": 0
    }
  },
  "edit_columns": {
    "additionalProp1": {
      "page": 0,
      "page_size": 0
    },
    "additionalProp2": {
      "page": 0,
      "page_size": 0
    },
    "additionalProp3": {
      "page": 0,
      "page_size": 0
    }
  },
  "keys": [
    "add_columns"
  ]
}
#Query taken from UI example above
r = requests.get(url, headers =client._headers, params = {'q': json.dumps(query)}) 
print(r.text) # '{"add_columns":[{"description":"","label":"Slice Name","name":"slice_name","required":true,"type":"String","unique":false,"validate":["<Length(min=1, max=250, equal=None, error=None)>"]}]}\n'
print(r.status_code) #200
#Assuming there is a query response, the chart will still fail since it has no edit_columns key
infos = r.json()
output = infos.get('edit_columns')
#Output is of NoneType
```

# Issues
1. The chart/_info API seems to need a query (q param)
2. There's no way to add a query the client object constructor
3. Even if a query was added, the Chart constructor will still fail since there's no "[edit_columns](https://github.com/opus-42/superset-api-client/blob/850a9070fcf37bb58492a2726f9838e71d278413/supersetapiclient/base.py#L106)"

#Question
Is there anything I can do to resolve this?
Was there a misconfiguration on my end?
[1]
https://superset.apache.org/docs/installation/running-on-kubernetes

**Comment by nogreintel** [comment]
@jackcan2

**Comment by opus-42** [comment]
Hello, thank you for reporting the issue. There seems to have been breaking changes in the Superset API in newest version (3.x). I having found one additional issue to the one you mentioned (namely, strict policy on CSRF Token) and I implemented a quick fix which will be release soon. 

I still need to some extra-tests to ensure compatibility depending on the version. Some extra development may be necessary in the future to allow API Client to be compatible with different Superset Versions. I'll keep you up to date.

**Comment by nogreintel** [comment]
thanks. I tested the changes and they seem to work for me.

A few more questions:

1. I don't see any documentation on how to create dashboards/charts. Is the preferred way of doing this something along the lines of:

``` python 
from supersetapiclient.client import SupersetClient
from supersetapiclient.dashboards import Dashboard

client = SupersetClient(host="http://localhost:8080", username="admin", password="admin",)

dashboard_tile = 'automation-test-board'

testdash = Dashboard(id=None, dashboard_title='automation-test-board', published=False)

client.dashboards.add(testdash) 
```

If so, it seems that defining `testdash.slug` is a prerequisite for this code to actually work as it errors out if no slug attribute is specified.
2. Are the create/delete operations  for superset resources on the road map to be developed/added?


Lastly, thanks again for your help.

**Comment by opus-42** [comment]
Hello @nogreintel, I have just release a new version on PyPi. Still need to check backward compatibility with older version.

For your question, yes slug seems now a pre-requisites for dashboards which was not in earlier version of Superset. 
As for the roadmap, yes the idea is to add all the functionality for basic object and to extend the client to the all the available objects. 

Feel free to contribute if you'd like to add some functionality. Help will be much appreciated 😄 ! 
I think we can close the issue now.
