### ISSUE TITLE
OAuth tokens are never refreshed

### ISSUE THREAD

**Issue by ecederstrand** [opus-42/superset-api-client#23]
While the client gets a refresh token from `/security/login`, it is never taken into account when the access token expires (after 10 minutes by default) and API returns an HTTP 401.

**Comment by ecederstrand** [comment]
Upstream patch submitted as https://github.com/opus-42/superset-api-client/pull/24

**Comment by mdeshmu** [comment]
Any examples on How to specify oauth provider when using this client?

**Comment by opus-42** [comment]
Hello, what do you mean by oauth provider ? Oauth providers are typically configured in Apache Superset server. As for the REST API, there is only an oauth mecanism provided for the API with tokens.

**Comment by mdeshmu** [comment]
I have okta integration with Apache superset. API swagger documentation says only db and ldap provider is supported. Can i use okta (oauth) provider to authenticate with API ?
If yes, an example would be helpful.

**Comment by ecederstrand** [comment]
You would have to provide your Superset configuration with a  custom `SecurityApi` implementation that implements okta auth, and pass that to the security manager. Then you can proceed to override `SupersetClient.authenticate()` in this package to allow authentication with okta.

**Comment by mdeshmu** [comment]
Any working example, be it with any provider would be really helpful.

**Comment by ecederstrand** [comment]
Here's the gist of what we have for a Superset API configured for KeyCloak auth:

```python
class OAuthSupersetClient(supersetapiclient.client.SupersetClient):
    def __init__(self, oauth_token, *args, **kwargs):
        self._oauth_token = oauth_token
        super().__init__(*args, **kwargs)

    def authenticate(self):
        # Authenticate with OAuth using our KeyCloak setup
        session = requests_oauthlib.OAuth2Session(token=self._oauth_token)
        response = session.post(
            self.login_endpoint,
            json={
                "provider": "oauth",
                "refresh": "true",
            },
            verify=self.verify,
        )
        response.raise_for_status()
        return response.json()
```

For the Superset part of the equation, it's better to ask for directions in a forum directly related to Superset itself.

**Comment by mdeshmu** [comment]
This is what i needed. Thanks.

**Comment by opus-42** [comment]
Could @mdeshmu open a new issue so that we can provide a mechanism to choose provider when creating SupersetClient ? 🙏

**Comment by mdeshmu** [comment]
@opus-42 created [29](https://github.com/opus-42/superset-api-client/issues/29) and [30](https://github.com/opus-42/superset-api-client/issues/30)
