### ISSUE TITLE
Add ability to choose a provider when creating client

### ISSUE THREAD

**Issue by mdeshmu** [opus-42/superset-api-client#29]
Add ability to choose a provider when creating client. Example below:

```
from supersetapiclient.client import SupersetClient

client = SupersetClient(
    host="http://localhost:8080",
    username="admin",
    password="admin",
    provider="okta",
)
```

**Comment by ecederstrand** [comment]
You already can? https://github.com/opus-42/superset-api-client/blob/develop/supersetapiclient/client.py#L32

**Comment by opus-42** [comment]
Hello, I think we can close this, the option is ended available at the initialisation of `SupersetClient`

However, we have to see how that package can support provider like Okta, see #23 and #30. I am not sure how this could be properly added to the library
