### ISSUE TITLE
Error: (insecure_transport) OAuth2 MUST utilize https

### ISSUE THREAD

**Issue by tector** [opus-42/superset-api-client#42]
My local superset environment is up and running via:

```bash
    docker compose -f docker-compose-non-dev.yml up
```

frontend is served at http://localhost:8088 (superset default)

I then tried to start your sample script:

```python
from supersetapiclient.client import SupersetClient

client = SupersetClient(
    host="http://localhost:8088",
    username="admin",
    password="admin",
)
```

which leads to this error:

```bash
  File "[...]/requests_oauthlib/oauth2_session.py", line 471, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

I don't want to use HTTPS for local testing.. so is there any workaround for this?

And if not: can you please update your README file for usage with HTTPS?

**Comment by CalumJEadie** [comment]
Hey @tector, I found this suggestion by Stift007 worked a treat (thanks @Stift007! :))

```python
import os 
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
```

https://github.com/requests/requests-oauthlib/issues/287#issuecomment-1036594426

**Comment by opus-42** [comment]
Hello, thank you for this information and addition. 

This will be added to the README file. I will therefore close this
